### ISSUE TITLE
[Bug]: Vercel 빌드 오류

### ISSUE THREAD

**Issue by JioChoi** [morethanmin/morethan-log#133]
### Describe the bug

Deploy 과정에서 빌드 오류가 뜨네요.

```
[12:36:17.521] Running build in San Francisco, USA (West) – sfo1
[12:36:17.567] Cloning github.com/JioChoi/JinseoBlog (Branch: main, Commit: 9be1ee2)
[12:36:17.706] Previous build cache not available
[12:36:18.289] Cloning completed: 720.733ms
[12:36:18.426] Running "vercel build"
[12:36:19.001] Vercel CLI 28.16.13
[12:36:19.315] Installing dependencies...
[12:36:19.680] yarn install v1.22.17
[12:36:19.779] [1/4] Resolving packages...
[12:36:20.023] [2/4] Fetching packages...
[12:36:41.313] [3/4] Linking dependencies...
[12:36:41.317] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[12:36:41.317] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[12:36:41.317] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[12:36:41.319] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[12:36:41.321] warning " > next-sitemap@3.1.32" has unmet peer dependency "@next/env@*".
[12:36:41.356] warning Workspaces can only be enabled in private projects.
[12:37:00.179] [4/4] Building fresh packages...
[12:37:00.665] Done in 40.99s.
[12:37:00.698] Detected Next.js version: 12.1.6
[12:37:00.700] Running "yarn run build"
[12:37:00.916] yarn run v1.22.17
[12:37:00.982] $ next build
[12:37:01.772] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[12:37:01.773] This information is used to shape Next.js' roadmap and prioritize features.
[12:37:01.773] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[12:37:01.773] https://nextjs.org/telemetry
[12:37:01.773] 
[12:37:01.860] info  - Checking validity of types...
[12:37:08.032] info  - Creating an optimized production build...
[12:37:47.357] info  - Compiled successfully
[12:37:47.358] info  - Collecting page data...
[12:37:49.712] 
[12:37:49.712] > Build error occurred
[12:37:49.714] TypeError: Cannot read properties of undefined (reading 'value')
[12:37:49.715]     at getPosts (/vercel/path0/.next/server/chunks/89.js:301:35)
[12:37:49.715]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[12:37:49.715]     at async getStaticPaths (/vercel/path0/.next/server/pages/[slug].js:387:19)
[12:37:49.715]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
[12:37:49.716]     at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
[12:37:49.716]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
[12:37:49.716]   type: 'TypeError'
[12:37:49.716] }
[12:37:49.780] error Command failed with exit code 1.
[12:37:49.806] Error: Command "yarn run build" exited with 1
```

어떻게 해야할까요...?

### To reproduce

https://github.com/JioChoi/JinseoBlog#getting-started
대로 따라했습니다.

### Browser

Google Chrome

### Validations

- [x] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by morethanmin** [comment]
안녕하세요 :) 아래 사진처럼 vercel에 환경변수가 설정되어 있을까요?

<img width="1228" alt="image" src="https://user-images.githubusercontent.com/72514247/223586570-e4667728-f62c-4956-b8e4-991eeebf50c7.png">

**Comment by linnilsupak** [comment]
Can you redeploy? I used to forgot adding environment and push the branch first and it build from the time I don't have environment.
