### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by kailew** [morethanmin/morethan-log#178]
### Describe the bug

Hi, I am trying to upload to vercel, and I am receiving this error: ```
Build error occurred
--
16:25:34.227 | TypeError: Cannot read properties of undefined (reading 'value')
16:25:34.227 | at getPosts (/vercel/path0/.next/server/chunks/463.js:180:35)
16:25:34.227 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
16:25:34.227 | at async getStaticPaths (/vercel/path0/.next/server/pages/[slug].js:531:19)
16:25:34.228 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
16:25:34.228 | at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
16:25:34.228 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
16:25:34.228 | type: 'TypeError'
16:25:34.228 | }
16:25:34.279 | error Command failed with exit code 1.
16:25:34.280 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
16:25:34.307 | Error: Command "yarn run build" exited with 1
16:25:35.034 | Deployment completed
16:25:34.644 | BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1

</body>
</html>```

### To reproduce

1. Go to ...
2. Click on ...
3. Scroll down to ..
upload to vercel

### Browser

Google Chrome

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by kailew** [comment]
my bad
