### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by smkplus** [morethanmin/morethan-log#207]
### Describe the bug

```
[11:10:38.950] Running build in Washington, D.C., USA (East) – iad1
[11:10:39.014] Cloning github.com/smkplus/morethan-log (Branch: main, Commit: 7707a1f)
[11:10:39.267] Cloning completed: 253.196ms
[11:10:39.324] Previous build cache not available
[11:10:39.413] Running "vercel build"
[11:10:39.919] Vercel CLI 30.2.1
[11:10:40.175] Installing dependencies...
[11:10:40.460] yarn install v1.22.17
[11:10:40.528] [1/4] Resolving packages...
[11:10:40.669] [2/4] Fetching packages...
[11:10:51.603] [3/4] Linking dependencies...
[11:10:51.605] warning "react-notion-x > react-image@4.0.3" has unmet peer dependency "@babel/runtime@>=7".
[11:10:51.606] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react@^15 || ^16".
[11:10:51.606] warning "react-notion-x > react-lazy-images@1.1.0" has incorrect peer dependency "react-dom@^15 || ^16".
[11:10:51.606] warning "react-notion-x > react-pdf > file-loader@6.2.0" has unmet peer dependency "webpack@^4.0.0 || ^5.0.0".
[11:10:51.608] warning " > next-sitemap@3.1.32" has unmet peer dependency "@next/env@*".
[11:10:51.631] warning Workspaces can only be enabled in private projects.
[11:10:58.869] [4/4] Building fresh packages...
[11:10:59.166] Done in 18.71s.
[11:10:59.195] Detected Next.js version: 12.1.6
[11:10:59.196] Running "yarn run build"
[11:10:59.402] yarn run v1.22.17
[11:10:59.444] $ next build
[11:11:00.065] Attention: Next.js now collects completely anonymous telemetry regarding usage.
[11:11:00.065] This information is used to shape Next.js' roadmap and prioritize features.
[11:11:00.065] You can learn more, including how to opt-out if you'd not like to participate in this anonymous program, by visiting the following URL:
[11:11:00.065] https://nextjs.org/telemetry
[11:11:00.066] 
[11:11:00.082] Browserslist: caniuse-lite is outdated. Please run:
[11:11:00.082]   npx browserslist@latest --update-db
[11:11:00.082]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[11:11:00.130] info  - Checking validity of types...
[11:11:05.005] info  - Creating an optimized production build...
[11:11:05.229] Browserslist: caniuse-lite is outdated. Please run:
[11:11:05.229]   npx browserslist@latest --update-db
[11:11:05.229]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[11:11:06.011] Browserslist: caniuse-lite is outdated. Please run:
[11:11:06.011]   npx browserslist@latest --update-db
[11:11:06.011]   Why you should do it regularly: https://github.com/browserslist/browserslist#browsers-data-updating
[11:11:33.540] info  - Compiled successfully
[11:11:33.541] info  - Collecting page data...
[11:11:35.253] 
[11:11:35.254] > Build error occurred
[11:11:35.255] TypeError: Cannot read properties of undefined (reading 'value')
[11:11:35.255]     at getPosts (/vercel/path0/.next/server/chunks/463.js:180:35)
[11:11:35.256]     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
[11:11:35.256]     at async getStaticPaths (/vercel/path0/.next/server/pages/[slug].js:565:19)
[11:11:35.257]     at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
[11:11:35.257]     at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
[11:11:35.257]     at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
[11:11:35.257]   type: 'TypeError'
[11:11:35.257] }
[11:11:35.313] error Command failed with exit code 1.
[11:11:35.313] info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
[11:11:35.335] Error: Command "yarn run build" exited with 1
[11:11:35.682] BUILD_UTILS_SPAWN_1: Command "yarn run build" exited with 1
```

### To reproduce

I did all steps but I had a build error!!!
I added environment variable too
this is my page on notion
https://tarry-honeydew-132.notion.site/04be91eab50f437aa0b44a6f34d1af91?v=8634bc3170784bf5837bf0a181ffcd47&pvs=4
I changed the config
```
const CONFIG = {
  // profile setting (required)
  profile: {
    name: "SeyedMortezaKamali",
    image: "/avatar.svg", // If you want to create your own notion avatar, check out https://notion-avatar.vercel.app
    role: "frontend developer",
    bio: "I develop everything using node.",
    email: "smkplus3d@gmail.com",
    linkedin: "",
    github: "",
    instagram: "",
  },
  projects: [
    {
      name: `morethan-log`,
      href: "https://github.com/smkplus/morethan-log",
    },
  ],
  // blog setting (required)
  blog: {
    title: "morethan-log",
    description: "welcome to morethan-log!",
    theme: "auto", // ['light', 'dark', 'auto']
  },

  // CONFIG configration (required)
  link: "https://morethan-log.vercel.app",
  since: 2022, // If leave this empty, current year will be used.
  lang: "en-US", // ['en-US', 'zh-CN', 'zh-HK', 'zh-TW', 'ja-JP', 'es-ES', 'ko-KR']
  ogImageGenerateURL: "https://og-image-korean.vercel.app", // The link to generate OG image, don't end with a slash
  seo: {
    keywords: ["Blog", "Website", "Notion"],
  },

  // notion configuration (required)
  notionConfig: {
    pageId: process.env.NOTION_PAGE_ID,
  },

  // plugin configuration (optional)
  googleAnalytics: {
    enable: false,
    config: {
      measurementId: "",
    },
  },
  googleSearchConsole: {
    enable: false,
    config: {
      siteVerification: "",
    },
  },
  utterances: {
    enable: false,
    config: {
      repo: "smkplus/morethan-log",
      "issue-term": "og:title",
      label: "💬 Utterances",
    },
  },
  cusdis: {
    enable: false,
    config: {
      host: "https://cusdis.com",
      appid: "", // Embed Code -> data-app-id value
    },
  },
  isProd: process.env.VERCEL_ENV === "production", // distinguish between development and production environment (ref: https://vercel.com/docs/environment-variables#system-environment-variables)
}

module.exports = { CONFIG }
```

### Browser

Windows 10

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by jackwillfly3235** [comment]
I have the same error, and not able to publish the site, 
do we have a solution yet ?  thanks

**Comment by smkplus** [comment]
@jackwillfly3235 finally I created my blog using hugo templates
