### ISSUE TITLE
[Bug]: Vercel 배포시 발생하는 문제입니다.

### ISSUE THREAD

**Issue by dydals3440** [morethanmin/morethan-log#228]
### Describe the bug

> Build error occurred
--
21:41:30.163 | TypeError: Cannot read properties of undefined (reading 'value')
21:41:30.163 | at getPosts (/vercel/path0/.next/server/chunks/463.js:180:35)
21:41:30.163 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
21:41:30.163 | at async getStaticPaths (/vercel/path0/.next/server/pages/[slug].js:565:19)
21:41:30.164 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:491:31)
21:41:30.164 | at async /vercel/path0/node_modules/next/dist/build/utils.js:632:119
21:41:30.164 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:79:20) {
21:41:30.164 | type: 'TypeError'
21:41:30.164 | }
21:41:30.210 | error Command failed with exit code 1.
21:41:30.211 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:41:30.231 | Error: Command "yarn run build" exited with 1

어느 부분에서 에러가 발생했는지 알고 싶습니다. 일단. Modify Before Deploy 부분은 수정했고, 노션 주소 링크도 환경변수에 뒷부분 추가해주었는데 왜 배포가 안되는지 알고 싶습니다!

### To reproduce

Vercel 배포중 발생한 에러입니다.

### Browser

mac

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by dydals3440** [comment]
해결되었습니다. 노션페이지 주소 전체를 복사하는 것이 아니었네요 ㅠㅠ 좋은 기능 담긴 블로그 제작해주셔서 감사합니다!
