### ISSUE TITLE
[Bug]: site.config.js에서 profile의 role을 변경했더니 TypeError가 발생합니다.

### ISSUE THREAD

**Issue by newdoin** [morethanmin/morethan-log#311]
### Describe the bug

role의 내용을 cloud-infra engineer로 변경 후 커밋하니 아래와 같은 에러가 발생합니다.

```
TypeError: Cannot read properties of undefined (reading '0')
--
21:49:33.476 | at /vercel/path0/.next/server/chunks/871.js:533:39
21:49:33.477 | at Array.filter (<anonymous>)
21:49:33.477 | at filterPosts (/vercel/path0/.next/server/chunks/871.js:532:6)
21:49:33.477 | at getStaticPaths (/vercel/path0/.next/server/pages/[slug].js:163:101)
21:49:33.477 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
21:49:33.477 | at async buildStaticPaths (/vercel/path0/node_modules/next/dist/build/utils.js:699:33)
21:49:33.477 | at async /vercel/path0/node_modules/next/dist/build/utils.js:1127:113
21:49:33.477 | at async Span.traceAsyncFn (/vercel/path0/node_modules/next/dist/trace/trace.js:103:20)
21:49:33.479 |  
21:49:33.479 | > Build error occurred
21:49:33.482 | Error: Failed to collect page data for /[slug]
21:49:33.483 | at /vercel/path0/node_modules/next/dist/build/utils.js:1158:15
21:49:33.483 | at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
21:49:33.483 | type: 'Error'
21:49:33.483 | }
21:49:33.544 | error Command failed with exit code 1.
21:49:33.545 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
21:49:33.567 | Error: Command "yarn run build" exited with 1
```

### To reproduce

See error

### Browser

MacOs

### Validations

- [X] Follow our [Code of Conduct](https://github.com/morethanmin/morethan-log/blob/main/.github/docs/CODE_OF_CONDUCT.md)
- [X] Check that there isn't [already an issue](https://github.com/morethanmin/morethan-log/issues) that reports the same bug to avoid creating a duplicate.

**Comment by AshtonJo** [comment]
저도 이런 에러가 뜨는데 고치신분있을까요?
